file_uploads = On
upload_max_filesize = 512M
post_max_size = 512M
memory_limit = 512M
max_execution_time = 300
max_input_time = 300
max_input_vars = 5000
realpath_cache_size = 4096K
realpath_cache_ttl = 600

opcache.enable=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
opcache.revalidate_freq=2
opcache.jit=1255
opcache.jit_buffer_size=128M
opcache.save_comments=1
opcache.enable_file_override=1
